name: Node.js CI - reutilizando accion-simple-compuesta
on:
  workflow_dispatch:
  push:
jobs:
  example_matrix:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
        version: [10, 12, 14]
        runs-on: ${{ matrix.os }}
    uses: amiguelGH/video-fsm-tres/.github/workflows/deploy-github-pages-base.yml@main
    with:
      target: ${{ matrix.version }}
    
