name: Node.js CI - reutilizando accion-simple-compuesta
on:
  workflow_dispatch:
  push:
jobs:
  test:
    strategy:
        matrix:
          number1: [1, 2, 3, 4, 5, 6, 7]
          number2: [7, 6, 5, 4, 3, 2, 1]
    uses: amiguelGH/video-fsm-tres/.github/workflows/deploy-github-pages-base.yml@main
    with:
      runner: ubuntu-latest
