name: Node.js CI - reutilizando accion-simple-compuesta
on:
  workflow_dispatch:
  push:
jobs:
  ci:
    name: run build process
    uses: amiguelGH/video-fsm-tres/.github/workflows/deploy-github-pages-base.yml@main
    #YOUR_ORG/GHA.workflows/.github/workflows/gha.workflows.build-node.yml@main
