

name: Node.js Package

on:
  push    # workflow_dispatch

permissions:
  id-token: write
  contents: read
  pages: write

  
jobs:
  example_matrix:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
        version: [10, 12, 14]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup Node  
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies    
        run: npm ci
      - name: Build Project
        run: npm run build

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          name: "github-pages"
          path: build

      - name: Deploy with gh-pages
        uses: actions/deploy-pages@v4
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: "github-pages"
          
  
