name: Build matriz

on: [push]

permissions:
  id-token: write
  contents: read
  pages: write

  
jobs:
  example_matrix:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
        version: [10, 12, 14]
        
        include:
          - os: ${{ matrix.os }}
           
            artifact_name: ${{ github.event.repository.name }}
            asset_name: ${{ github.event.repository.name }}-${{ os }}-${{ version }}          
    
    runs-on: ${{ matrix.os }}
       
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup Node  
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies    
        run: npm ci
      - name: Build Project
        run: npm run build

      #- name: Upload artifacts
      #  uses: actions/upload-pages-artifact@v3
      #  with:
      #    name: "github-pages"
      #    path: build
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: github-pages-${{ matrix.os }}-${{ matrix.version }}
          path: build/github-pages-${{ matrix.os }}-${{ matrix.version }}

      - name: Deploy with gh-pages
        uses: actions/deploy-pages@v4
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: build/github-pages-${{ matrix.os }}-${{ matrix.version }}
          
  

