on: [push]

jobs:
  ReuseableMatrixJobForDeployment:
      runs-on: ubuntu-latest
      name: A job to say hello
      strategy:
        matrix:
         target: [dev, stage, prod]    
         
         
      steps:   
         # To use this repository's private action,
         # you must check out the repository
          - name: Hello world action step
            uses: ./ # Uses an action in the root directory
            id: hellodeploy-git-pages.yml 
            with:
               target: ${{ matrix.target }}
